apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-dp
  labels:
    app: kuber-dp
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 3 # кол-во модулей, кот можно создать сверх необходимого кол-ва подов
      maxUnavailable: 1
    type: RollingUpdate # тип стратегии
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: kuber-app
        image: slisebo/homework2:1.3
        ports:
        - containerPort: 8000
