apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: kuber-ingres
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuber-service
            port:
              number: 8000
